### PR TITLE
Bump maximum Terraform version

### PR DESCRIPTION
**Pull request by Lillecarl**
Bump TF version so we can use the newer 4.x features in projects depending on this module.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

Not sure if less than 5 is appropriate, but it was less than 4 before and there was no incompabilities when i bumped the version across our infra (related to EFS)

### CODE REVIEW

**Comment by adammeghji** [comment]
If this looks good, would love to see this merged :) Thanks!

**Comment by Lillecarl** [comment]
@adammeghji After reading other modules I see it's rare people put in upper version constraints at all, they seem to leave that part to the end user mostly. We're using my fork as module source rather than the released one right now to move to AWS 4.x provider.

**Comment by Lillecarl** [comment]
DNXLabs out of business?

**Review by cgtarmenta — APPROVED** [review]
I don't see any issues changing the max aws-cli version to work over version 4.

**Review by adammeghji — APPROVED** [review]

**Comment by darraghenright** [comment]
Hi folks 👋 

Just encountered the dependency issue that this PR addresses. Does anyone know if this PR will be merged in the near future? Thanks.

**Review by sobi3ch — APPROVED** [review]

**Comment by sobi3ch** [comment]
@Lillecarl maybe you would like to take over this module (by forking). Looks like author doesn't have time to maintain it any more.

**Comment by Lillecarl** [comment]
Hi @sobi3ch!

I've never pushed a module to the TF registry and I honestly don't wan't external orgs to depend on me. If i were you I'd fork my repo and use the git module syntax in your code to fetch the module from your own fork.

Since this PR I've changed from a DevOps role to an SRE role where it's more automation of servers than cloud environments, I'm only on assist mode with the DevOps team now.

Though the module works great with this path still, so I'd definitely fork and use it :)

Good luck!

**Review by sanfoobar — APPROVED** [review]

**Review by cgtarmenta — APPROVED** [review]

**Comment by Lillecarl** [comment]
I'd say it's rather obvious DNXLabs doesn't care about this anymore, I guess none of their active clients are using EFS anymore.
@helderklemp @adenot is this how you run open-source projects? 🤔

**Review by adenot — APPROVED** [review]

**Comment by Lillecarl** [comment]
Thank you 😄

**Pull request merged**
